import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Lato,
  Nunito,
  Raleway,
  Roboto,
  Sora,
} from "next/font/google";
import "./globals.css";
import { AuthButtons } from "@/components/auth-buttons";
import { Open_Sans } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  // weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sora.className} antialiased`}>
        <div className="p-2 border-b flex items-center justify-end">
          <AuthButtons />
        </div>
        {children}
      </body>
    </html>
  );
}
